### ISSUE TITLE
Problem with Pyqt4

### ISSUE THREAD

**Issue by kapranos** [josecurioso/Tusubtitulo.com-Downloader-Unofficial-#1]
Hi 

Nice work with this.

I have the next issue when i execute your script:

 File "service_GUI.py", line 2, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: No module named PyQt4

Can you help me?

thanks

**Comment by josecurioso** [comment]
Before being able to import parts of Qt you need to install PyQt4 after downloading from [here](https://riverbankcomputing.com/software/pyqt/download). Keep in mind your Python version when installing PyQt.
