### ISSUE TITLE
Ayuda con el addon de Kodi

### ISSUE THREAD

**Issue by susobaco** [josecurioso/Tusubtitulo.com-Downloader-Unofficial-#2]
Hola, buena iniciativa, la verdad es que no tengo ni idea de python. (y eso que tengo un par de manuales y debería ponerme). Supongo que ya habrás visto que hay un proyecto descontinuado que en su día funcionó: https://github.com/ElHappy/service.subtitles.tusubtitulo . No se si sería muy dificil "adaptarlo" a tu script.
Si puedo de servirte de ayuda en algo, aquí me tienes.
Salud!

**Comment by josecurioso** [comment]
Hay novedades con el tema del addon, ya está hecho! queremos llevar este repo por otro camino así que el addon está en [https://github.com/josecurioso/service.subtitles.tusubtitulo](https://github.com/josecurioso/service.subtitles.tusubtitulo) y pronto será añadido al repositorio oficial de Kodi desde la version Krypton en adelante. Se que ha pasado un tiempo pero por fin está listo.

**Comment by susobaco** [comment]
Genial! muchas gracias, los que tenemos problemas auditivos te lo agradecemos de corazón, Esperemos que la web no cambie tan a menudo y permita su descargas. Reitero el agradecimiento.
