### ISSUE TITLE
Error fetching a nonexistent string

### ISSUE THREAD

**Issue by carlosmanri** [josecurioso/Tusubtitulo.com-Downloader-Unofficial-#7]
When you try to look for a serie that not exists in the database you get an Exception

![screenshot_20170526_151742](https://cloud.githubusercontent.com/assets/9149238/26496287/264707ca-4227-11e7-89a8-f0c027af708c.png)

**Comment by josecurioso** [comment]
Working on it

**Comment by josecurioso** [comment]
The error is no fixed
